# self attention with out weights

In [1]:
import torch 

In [4]:
inputs=torch.randn(5,3)

In [44]:
query=inputs[2]

attn_score=torch.empty(inputs.shape[0])

for i,val in enumerate(inputs):
    attn_score[i]=torch.dot(val,query)


print(f"the input:{query}")
print(f"the attention score:{attn_score}")


the input:tensor([ 0.1254, -0.5530, -0.4138])
the attention score:tensor([ 0.1792, -0.7304,  0.4928, -1.0860, -0.7304])


# we know make the attention weight by normalizing the attention score

In [11]:
attn_weight=attn_score/attn_score.sum()
print(f"the attention score is: {attn_score}")
print(f"the attention weight is:{attn_weight}")

the attention score is: tensor([ 0.1792, -0.7304,  0.4928, -1.0860, -0.7304])
the attention weight is:tensor([-0.0956,  0.3896, -0.2629,  0.5793,  0.3896])


In [22]:
def local_softmax(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)

In [24]:
local_softmax(attn_score)

tensor([0.2894, 0.1165, 0.3959, 0.0817, 0.1165])

In [28]:
torch.softmax(attn_score,dim=0)

tensor([0.2894, 0.1165, 0.3959, 0.0817, 0.1165])

# calculate the context vector

In [43]:
#with respect to the third(2) token
context_value=torch.zeros(query.size())
for i,val in enumerate(inputs):
    context_value+=attn_weight[i]*val

print(context_value)

tensor([-0.3275,  1.9661,  0.5232])


# extracting context vector from all inputs

In [47]:
inputs = torch.tensor(
[[0.43, 0.15, 0.89],
[0.55, 0.87, 0.66], 
[0.57, 0.85, 0.64],
[0.22, 0.58, 0.33], 
[0.77, 0.25, 0.10],
[0.05, 0.80, 0.55]]
)


In [56]:
#attention score is
attention_score=torch.zeros(6,6)

for i,i_val in enumerate(inputs):
    for j,j_val in enumerate(inputs):
        attention_score[i,j]=torch.dot(i_val,j_val)

In [60]:
#we can also transpose the values here
att_score=inputs@inputs.T

In [61]:
att_score

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [57]:
print(attention_score)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [62]:
#using torch softmax
attnetion_weight=torch.softmax(att_score,dim=1)

In [63]:
attnetion_weight

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [65]:
attnetion_weight.sum(dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [66]:
context_vector=attnetion_weight@inputs

In [67]:
context_vector

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])